### ISSUE TITLE
Code Blocks Direction

### ISSUE THREAD

**Issue by Farhaduneci** [bit-orbit/the-secret-bit#17]
### سلام، امیداورم که حالتون خوب باشه ツ
ممنون بابت پروژه، من بخشی از متن هارو خوندم و متوجه ی مشکل کوچیک داخل Theme سایت شدم که فکر می‌کنم حل کردنش می‌تونه خوب باشه.

تگ های _pre_ که داخل اونها از تگ _code_ استفاده شده RTL شدن که این باعث می‌شه $ اول نمونه کد های موجود آخرشون چاپ بشه و این ی مقدار گیج کننده هستش :face_with_spiral_eyes:.

![image](https://user-images.githubusercontent.com/53964770/164889237-22a0b884-2686-444d-bb71-36c5ad8ddb8d.png)

به نظرم میشه این مشکل رو با اضافه کردن این استایل داخل فایل استایل های custom بر طرف کرد.
```css
pre.language-bash {
    direction: ltr;
}
```
داخل فایل های ‌MD دیدم که برای درست کردن این مشکل کد هارو با `<div dir='ltr'>` نوشتن، اما خب همه جا یادشون نبوده و خیلی ها RTL موندن. اگه به نظرتون این استایل می‌تونه مشکل رو حل کنه می‌تونم با خوشحالی Pull Reqest بفرستم.

**Comment by shabane** [comment]
سلام. خیلی ممنون. امیدوارم حال شما هم خوب باشه.
و ممنونم بابت مشارکتتون.
 

درسته. ما خیلی بابتپول ریکوئست ممنونیم. و البته این ایشو که به خوبی همه چیز رو گفته بود. ممنون واقعا. امیدوارم بیشتر باهم همکاری داشته باشیم.
